version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:15.2.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Confirm current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          key:
            - app-{{ checksum"package.json }}
            - app-
      - run:
          name: Install yarn
          command: npm install -g yarn
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key:
            - app-{{ checksum"package.json }}
